### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by asdfqwer2015** [ammirato/target_driven_instance_detection#5]
Hi:
  En, I found the memory(not cuda memory) keep growing when training, anywhere leads memory leak?
  I'm training the model with configAVD2.py, up to 45Gb mem allocated in epoch1, and always get killed due to my mem environment limit. the config file is modified like https://github.com/ammirato/target_driven_instance_detection/issues/1#issuecomment-379806941. And I only modified params like dataset dir etc except NUM_WORKERS=1.
(RESIZE_IMG = 1).
  Did I miss something?
  Thanks.

**Comment by asdfqwer2015** [comment]
This seems to be a pytorch bug https://github.com/pytorch/pytorch/issues/13246 .
Anyway, can this model be trained with num_workers > 0? Single thread is too slow.

**Comment by ammirato** [comment]
I assume you are not using pytorch 0.3.X when experiencing this bug
