### ISSUE TITLE
unable to load trained model

### ISSUE THREAD

**Issue by asdfqwer2015** [ammirato/target_driven_instance_detection#7]
Hi:
  I run `test_tdid.py` with downloaded trained model `TDID_AVD2.h5` but got an error in loading model step:
KeyError: "Unable to open object (object 'features.1.num_batches_tracked' doesn't exist)"
  What did I missed?
  Thanks.

**Comment by ammirato** [comment]
It seems like there is some difference between the structure/names of the variables in the saved file and those in the model in your code.

  If you are not using pytorch 0.3.X, it is likely updates to pytorch changed variable names, etc. That model file is likely not be compatible with later versions of pytorch.

**Comment by asdfqwer2015** [comment]
Thanks.
I ignored all param likes '*.num_batches_tracked' since it's newly added to pytorch for bn and only used for training phase, now it load successfully, and the model works.
:)
